classDiagram
    class Battle
    class BattleCommand
    class BattleResult
    class BattleTurn

    Battle --> Hero
    Battle --> Monster
    Battle --> Spell
    Battle --> Weapon
    Battle --> Inventory
    Battle --> BattleCommand